#' Fit point process models to one FOV of a `SpatialExperiment`
#' object
#'
#' @param spe `SpatialExperiment`; object subset to a single image
#' @param model `character`; the `spatstat.model` function to use for computation.
#' Typically one of `ppm`, `kppm` or `dppm`.
#' @param marks `character`; the column with the labels e.g. cell types
#' @param formula `formula`; the formula to pass to the `ppm` function
#' @param family `detpointprocfamily`; Family to use in the point process model.
#' One of `dppGauss`, `dppMatern`, `dppCauchy`, `dppBessel` or `dppPowerExp`
#' @param threshold `numeric`; a threshold to apply on the minimum number of
#' points a point pattern needs to have to fit a `ppm` model to it.
#' @param cellspacing `numeric` how much spacing should be accounted for in the 
#' Hardcore process due to the cell body
#' @param ... other parameters passed on to `ppm` model from `spatstat.model`
#'
#' @returns `list`; result from a `dppm` model in `spatstat.model`
#' @export
#'
#' @examples
#' spe <- SpatialDatasets::spe_Keren_2018()
#' speSub <- subset(spe, , imageID == "5")
#'
#' mdl <- fitModel(spe = speSub,
#'                 marks = "cellType",
#'                 formula = as.formula("Keratin_Tumour ~ distfun(CD8_T_cell)")
#' )
#' 
#' @importFrom mgcv s
#' @importFrom spatstat.model dppm
#' @importFrom spatstat.model kppm
#' @importFrom spatstat.model ppm
#' @import spatstat.geom
fitModel <- function(spe,
                     model = "ppm",
                     marks,
                     formula,
                     family = spatstat.model::dppGauss(),
                     threshold = NULL,
                     cellspacing = NULL,
                     ...){
  #some type assertions
  stopifnot(is(spe, "SpatialExperiment"))
  stopifnot(is(marks, "character"))
 

  #convert spe to ppp object
  pp <- speToPPP(spe, marks = marks)

  response <- as.character(formula.tools::lhs(formula))

  #subset the ppp object to the response mark
  ppResponse <- spatstat.geom::unmark(pp[pp$marks %in% response, drop = TRUE])
  if(!is.null(threshold) && spatstat.geom::npoints(ppResponse) <= threshold){
    message(paste0("There were less than ",  threshold, " points to compute distances too"))
        return(NULL)
  }
  #rhs variables of the formula
  rhs <- formula.tools::rhs(formula)
  #separate variables from terms (variable plus functions)
  rhsVars <- all.vars(rhs)
  rhs_terms <- attr(stats::terms(formula), "term.labels")

  #extract and store response
  data <- list(x = SpatialExperiment::spatialCoords(spe)[,SpatialExperiment::spatialCoordsNames(spe)[1]],
    y = SpatialExperiment::spatialCoords(spe)[,SpatialExperiment::spatialCoordsNames(spe)[2]])
  
  data[[response]] = ppResponse

  ### begin code generated by claude.ai ### 
  # build env with ppp objects to evaluate terms in
  if(length(rhs_terms) == 0){
    # intercept only model - no covariate processing needed
    newElements <- list()
    formula <- stats::as.formula(paste(response, "~ 1"))
  } else {
    eval_env <- list2env(
      sapply(rhsVars[!rhsVars %in% c("x","y")], function(v){
        spatstat.geom::unmark(pp[pp$marks %in% v, drop = TRUE])
      }, simplify = FALSE),
      parent = list2env(as.list(getNamespace("spatstat.explore")), 
                    parent = getNamespace("spatstat.geom"))
    )
    
    newElements <- list()
    new_rhs_terms <- rhs_terms
    
    for(i in seq_along(rhs_terms)){
      term <- rhs_terms[i]
      parsed <- tryCatch(eval(parse(text = term), envir = eval_env), error = function(e) NULL)
      if(!is.null(parsed) && (spatstat.geom::is.im(parsed) ||
                              is.function(parsed) ||
                              spatstat.geom::is.owin(parsed) ||
                              spatstat.geom::is.tess(parsed) ||
                              is.numeric(parsed))){
        safe_name <- make.names(term)
        newElements[[safe_name]] <- parsed
        new_rhs_terms[i] <- safe_name
      }
    }
    
    new_rhs <- paste(new_rhs_terms, collapse = " + ")
    formula <- stats::as.formula(paste(response, "~", new_rhs))
  }
  ### end code generated by claude.ai ### 

  data <- c(data, newElements)

  #fit the model. If there is a cellspacing value indicated, this will be a
  #Gibbs point process with a Hardcore spacing between points.
  if(!is.null(cellspacing)){
    mdl <- do.call(model, 
      args = list(Q = formula,
                  family = family,
                  data = data,
                  interaction = spatstat.model::Hardcore(cellspacing),
                  use.gam = TRUE,
                  ...)
    )
  }else{
    #else Poisson process without spacing
    mdl <- do.call(model, 
      args = list(Q = formula,
                  family = family,
                  data = data,
                  use.gam = TRUE,
                  ...)
    )
  }
  #add covariates to the mdl list
  mdl$colData <- colData(spe)
  return(mdl)
}
